version: '3.7'

services:
  web:
    image: 'rememberme:dev'
    build:
      target: development_build
      context: .
      cache_from:
        - 'rememberme:dev'
        - 'rememberme:latest'
        - '*'
      args:
        DJANGO_DEV: development
    command: python -Wd manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data:

